albumy/blueprints/auth.py
"""
@FileName：auth.py
@Author：stone
@Time：2023/5/13 20:56
@Description:
"""

from flask import Blueprint, url_for, flash, redirect, render_template
from flask_login import current_user, login_user, login_required, logout_user

from albumy.forms.auth import RegisterForm, LoginForm, ForgetPasswordForm, ResetPasswordForm
from albumy.models import User
from albumy.extensions import db
from albumy.settings import Operations
from albumy.utils import generate_token, redirect_back, validate_token
from albumy.emails import send_confirm_email, send_reset_password_email

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return (url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        # 生成token
        token = generate_token(user=user, operation='confirm')
        send_confirm_email(user=user, token=token)
        flash("确认发送邮件,点击按钮", 'info')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.validate_password(form.password.data):
            login_user(user, form.remember_me.data)
            flash("登录成功", 'info')
            return redirect_back()
        flash("邮箱或者密码无效", 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash("退出登录", 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('main.index'))
    if validate_token(user=current_user, token=token, operation=Operations.CONFIRM):
        flash("账户确认成功", 'success')
        return redirect(url_for('mian.index'))
    else:
        flash("token过期了", 'danger')
        return redirect(url_for('.resend_confirmation'))


@auth_bp.route('/resend-confirm-email')
@login_required
def resend_confirm_email():
    if current_user.confirmed:
        return redirect(url_for('main.index'))
    token = generate_token(user=current_user, operation=Operations.CONFIRM)
    send_confirm_email(user=current_user, token=token)
    flash("新的邮件已发送", 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('forget-password', methods=["GET", "POST"])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash("密码重置邮件已发送,请查收", 'info')
            return redirect(url_for('.login'))
        flash('无效的邮件', 'warning')
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('mian.index'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is None:
            return redirect(url_for('main.index'))
        if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD, new_password=form.password.data):
            flash("密码已更新", 'success')
            return redirect(url_for('.login'))
        else:
            flash("无效的链接", 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)

albumy/blueprints/main.py
# -*- coding: utf-8 -*-
import os

from flask_dropzone import random_filename
from flask import render_template, Blueprint, request, current_app, send_from_directory
from albumy.decorators import confirm_required, permission_required
from flask_login import login_required, current_user

from albumy.models import Photo
from albumy.extensions import db
from albumy.utils import resize_image

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    return render_template('main/index.html')


@main_bp.route('/upload', methods=['POST', 'GET'])
@login_required  # 验证登录状态
@confirm_required  # 验证确认状态
@permission_required('UPLOAD')  # 验证权限
def upload():
    if request.method == "POST" and 'file' in request.files:
        # 获取图片文件对象
        f = request.files.get('file')
        # 生成随机的文件名
        filename = random_filename(f.filename)
        # 保存图片
        f.save(os.path.join(current_app.config['ALBUMY_UPLOAD_PATH'], filename))
        # 裁剪图片
        filename_s = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['small'])
        filename_m = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['medium'])
        photo = Photo(
            # 创建文件记录
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object()
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/explore')
def explore():
    return render_template('main/explore.html')

albumy/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
        <title>{% block title %}{% endblock %} - Albumy</title>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {% block styles %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        {% endblock styles %}
    {% endblock head %}
</head>

<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <img src="{{ url_for('static', filename='favicon.ico') }}" alt="Albumy">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('main.index', 'Home') }}
                    {{ render_nav_item('main.explore', 'Explore') }}
                    <form class="form-inline my-2 my-lg-0">
                        <input type="text" name="q" class="form-control mr-sm-1" placeholder="Photo, tag or user"
                               required>
                        <button class="btn btn-light my-2 my-sm-0" type="submit">
                            <span class="oi oi-magnifying-glass"></span>
                        </button>
                    </form>
                </div>
                <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('main.upload') }}" title="Upload">
                        <span class="oi oi-cloud-upload"></span>&nbsp;&nbsp;
                    </a>
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            {{ current_user.name }}<span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <h6 class="dropdown-header">Logged in as {{ current_user.username }}</h6>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                <span class="oi oi-power-standby"></span> Logout
                            </a>
                        </div>
                    </div>
                {% else %}
                    <a class="btn btn-outline-primary" href="{{ url_for('auth.login') }}">Login</a>&nbsp;&nbsp;
                    <a class="btn btn-primary" href="{{ url_for('auth.register') }}">Join Albumy</a>
                {% endif %}
                </div>
            </div>
        </div>
    </nav>
{% endblock %}

<main>
    <div class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}
        {% block content %}{% endblock %}
        {% block footer %}
            <footer>
                <p class="float-left">
                    <small>&copy; 2018
                        <a href="http://greyli.com" title="Written by Grey Li">Grey Li</a> -
                        <a href="https://github.com/greyli/albumy" title="Fork me on GitHub">GitHub</a> -
                        <a href="http://helloflask.com" title="A HelloFlask project">HelloFlask</a>
                    </small>
                </p>
                <p class="float-right">
                    <small>Capture and share every wonderful moment.</small>
                </p>
            </footer>
        {% endblock %}
    </div>
</main>

{% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
{% endblock %}
</body>
</html>

albumy/templates/macros.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>