albumy/forms/main.py
"""
@FileName：main.py
@Author：stone
@Time：2023/5/13 20:56
@Description:
"""

albumy/blueprints/auth.py
"""
@FileName：auth.py
@Author：stone
@Time：2023/5/13 20:56
@Description:
"""

from flask import Blueprint, url_for, flash, redirect, render_template
from flask_login import current_user, login_user, login_required, logout_user

from albumy.forms.auth import RegisterForm, LoginForm, ForgetPasswordForm, ResetPasswordForm
from albumy.models import User
from albumy.extensions import db
from albumy.settings import Operations
from albumy.utils import generate_token, redirect_back, validate_token
from albumy.emails import send_confirm_email, send_reset_password_email

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return (url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        # 生成token
        token = generate_token(user=user, operation='confirm')
        send_confirm_email(user=user, token=token)
        flash("确认发送邮件,点击按钮", 'info')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.validate_password(form.password.data):
            login_user(user, form.remember_me.data)
            flash("登录成功", 'info')
            return redirect_back()
        flash("邮箱或者密码无效", 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash("退出登录", 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('main.index'))
    if validate_token(user=current_user, token=token, operation=Operations.CONFIRM):
        flash("账户确认成功", 'success')
        return redirect(url_for('mian.index'))
    else:
        flash("token过期了", 'danger')
        return redirect(url_for('.resend_confirmation'))


@auth_bp.route('/resend-confirm-email')
@login_required
def resend_confirm_email():
    if current_user.confirmed:
        return redirect(url_for('main.index'))
    token = generate_token(user=current_user, operation=Operations.CONFIRM)
    send_confirm_email(user=current_user, token=token)
    flash("新的邮件已发送", 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('forget-password', methods=["GET", "POST"])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash("密码重置邮件已发送,请查收", 'info')
            return redirect(url_for('.login'))
        flash('无效的邮件', 'warning')
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('mian.index'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is None:
            return redirect(url_for('main.index'))
        if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD, new_password=form.password.data):
            flash("密码已更新", 'success')
            return redirect(url_for('.login'))
        else:
            flash("无效的链接", 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)

albumy/blueprints/main.py
# -*- coding: utf-8 -*-
import os

from flask_dropzone import random_filename
from flask import render_template, Blueprint, request, current_app, send_from_directory
from albumy.decorators import confirm_required, permission_required
from flask_login import login_required, current_user

from albumy.models import Photo
from albumy.extensions import db
from albumy.utils import resize_image

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    return render_template('main/index.html')


@main_bp.route('/upload', methods=['POST', 'GET'])
@login_required  # 验证登录状态
@confirm_required  # 验证确认状态
@permission_required('UPLOAD')  # 验证权限
def upload():
    if request.method == "POST" and 'file' in request.files:
        # 获取图片文件对象
        f = request.files.get('file')
        # 生成随机的文件名
        filename = random_filename(f.filename)
        # 保存图片
        f.save(os.path.join(current_app.config['ALBUMY_UPLOAD_PATH'], filename))
        # 裁剪图片
        filename_s = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['small'])
        filename_m = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['medium'])
        photo = Photo(
            # 创建文件记录
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object()
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/explore')
def explore():
    return render_template('main/explore.html')

albumy/blueprints/user.py
"""
@FileName：user.py
@Author：stone
@Time：2023/5/13 20:56
@Description:
"""
from flask import Blueprint, render_template
from albumy.models import User

user_bp = Blueprint('user', __name__)


@user_bp.route('/<username>')
def index(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user/index.html', user=user)

albumy/templates/main/explore.html
{% extends 'base.html' %}

{% block title %}Explore{% endblock %}

{% block content %}
{% endblock %}

albumy/templates/main/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
                <img src="{{ url_for('static', filename='images/index.jpg') }}" class="rounded img-fluid">
            </div>
            <div class="col-md-4 align-self-center">
                <h1>Albumy</h1>
                <p>Capture and remember every wonderful moment.</p>
                <p><a class="btn btn-primary btn-lg" href="{{ url_for('auth.register') }}">Join Now</a></p>
            </div>
        </div>
    </div>
{% endblock %}

albumy/templates/main/upload.html
{% extends 'base.html' %}

{% block title %}Upload{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dropzone.min.css') }}" type="text/css">
    {{ dropzone.style('margin: 20px 0; border: 2px dashed #0087F7; min-height: 400px;') }}
{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Upload</h1>
    </div>
    <div class="row">
        <div class="col-md-12">
            {{ dropzone.create(action='main.upload') }}
            <a class="btn btn-light float-right" href="{{ url_for('user.index', username=current_user.username) }}">
                Done
            </a>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/dropzone.min.js') }}"></script>

    {{ dropzone.config() }}
{% endblock %}